version: '3'
services:
  mysql_master:
    image: mysql:8
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/data:/var/lib/mysql

  mysql_slave:
    image: mysql:8
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
      - ./slave/data:/var/lib/mysql
  
  mysql_slave2:
    image: mysql:8
    env_file:
      - ./slave2/mysql_slave.env
    container_name: "mysql_slave2"
    restart: "no"
    ports:
      - 6606:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave2/my.cnf:/etc/mysql/my.cnf
      - ./slave2/data:/var/lib/mysql


